"""empty message

Revision ID: ecef3620c073
Revises: c02f14cefab0
Create Date: 2018-10-24 14:57:07.862656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecef3620c073'
down_revision = 'c02f14cefab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_agent', sa.String(length=100), nullable=True))
    op.alter_column('session', 'token',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('session', 'browser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('browser', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('session', 'token',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_column('session', 'user_agent')
    # ### end Alembic commands ###
